name: My first Workflow

on: 
    workflow_dispatch: 

jobs:
    First_Job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: list and read file
          run: |
               echo "Welcome to my first work flow"
               ls
               cat README.md
        - name: Gnerate ACSII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWR" >> dragon.txt
