name: ASCII Art Workflow

on:
  push:
  

jobs:
  ascii-art:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ASCII Artwork Shell Script
        uses: ./ascii artwork.sh
