name: ASCII Art Workflow

on:
  push:
  

jobs:
  ascii-art:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list files in repo
        run: ls -ltra
        
      - name: ASCII Artwork Shell Script
        run: ./ascii artwork.sh
