name: matrix configration

on:
    push:
    workflow_dispatch: 

jobs:
    deploy:
        strategy: 
         fail-fast: false
         max-parallel: 2
         matrix:
            os: [ubuntu-latest, ubuntu-22.04, window-latest]
            images: [hello-world, alpine]
            exclude:
            - images: alpine
              os: window-latest
            include:
            - images: amd64/alpine
              os: ubuntu-22.04


        runs-on: ${{matrix.os}}
        steps:
            - name: Echo docker detail
              run: docker info
            
            - name: run docker image ${{matrix.os}}
              run: docker run ${{matrix.images}}