name: multiple jobs 

on:
  push:
  

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
        - name: Install cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWR" >> dragon.txt

        - name: Upload dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: dragon text file artifact
            path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
        - name: download dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon text file artifact
            

        - name: Test file exsit
          run: grep -i "dragon" dragon.txt


  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
        - name: download dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon text file artifact
            
        - name: read file
          run: cat dragon.txt

        - name: depoly
          run: echo Deploying.....